version: '3.8'

services:
  postgres:
    image: postgres:13
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: usersdb
    ports:
      - "5433:5432"   # mapeo: host:container -> accede desde localhost:5433
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
